### PR TITLE
Add code from eff-functions

### PR DESCRIPTION
**Pull request by paf31**
The code is copied verbatim, just changing the module name and adding some spacing in the comments.

@hdgarrood The original code has no license file, so I inferred the MIT license from the `bower.json` file? I'll add that to the LICENSE file here if you can just confirm that's okay.

### CODE REVIEW

**Review by hdgarrood — APPROVED** [review]

**Comment by hdgarrood** [comment]
Yep, that's fine by me.

**Comment by paf31** [comment]
Actually, @hdgarrood, would you mind modifying the LICENSE file if you'd like it to be modified?

I think we should also discuss what the copyright notices should say/mean, at some point. It's not clear to me what "PureScript" identifies.

**Comment by hdgarrood** [comment]
I'm happy leaving the license file in this repo as it is regarding these changes.

In the longer term, do you think it would make sense to list contributors' names instead of just writing "PureScript"?

**Comment by paf31** [comment]
Yes, I would prefer that. I've been thinking the same recently :)

**Pull request merged**
